#! /bin/sh

gpg -d debug-keystore.gpg > ~/letrack-debug.keystore
gpg -d release-keystore.gpg > ~/letrack-release.keystore

gpg -d google_maps_api_release.xml.gpg > app/src/release/res/values/google_maps_api.xml
gpg -d google_maps_api_debug.xml.gpg > app/src/debug/res/values/google_maps_api.xml
